language: elixir
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
  - PGPORT=5433
elixir:
  - 1.9.0
otp_release:
  - 22.0
env:
  - MIX_ENV=test
cache:
  directories:
    - deps
    - _build/
    - apps/data/deps/
    - apps/data/_build/
branches:
  only:
  - master
install:
  - sudo -u postgres psql -p 5433 -c "create user grapevine with superuser password 'password';"
  - cp .travis/test.exs config/test.extra.exs
  - cp .travis/test.exs apps/data/config/test.extra.exs
  - mix local.rebar --force
  - mix local.hex --force
  - mix do deps.get, compile
  - cd apps/data && mix do deps.get, compile && cd ../..
  - mix do ecto.create, ecto.migrate
  - nvm install 10.13.0 && nvm use 10.13.0
  - cd assets && yarn install && cd ..
script:
  - ./verify.sh
